;try to import the eglot.el
; or find the way to import? or spy the import stack.
;(use-package eglot)
;(require 'package)
;(package-initialize)
(global-company-mode)
;(add-hook 'find-file-hook 'global-company-mode)
;(add-hook 'after-init-hook 'global-company-mode)
;(add-hook 'find-file-hook 'company-mode)
;(add-hook 'after-init-hook 'company-mode)
;(add-hook 'find-file-hook 'company-complete-common)
;(autoload 'company-mode)
;(eglot-completion-at-point)
;(eglot-ensure)
(setq company-idle-delay 0)
;(find-file "company2.sh");wtf is going on?
(insert "a")
;(company-mode)
;(company-complete-common)
;(require 'lsp-mode)
;(lsp)
;(print "init done?")
;(apply #'eglot--connect (eglot--guess-contact));no def here.
;(describe-function #'lsp-mode)
;(print-buffer)
;(describe-function #'eglot)
;(eglot 'sh-mode (project-current) 'eglot-lsp-server 'eglot-server-programs nil)
;(find-file "lsp.sh"); not executing.
;(run-with-timer 2 2 #'eglot-completion-at-point)
;(run-with-idle-timer eglot-completion-at-point)
;(package-install 'helm)
;(ielm) in buffer, not stdout.
;(defun find-symbols-having-properties (properties)
;  (let (ret)
;    (mapatoms (lambda (s)
;                (when (cl-loop for prop in properties
;                               thereis (get s prop))
;                    (push s ret))))
;    ret))
;(find-symbols-having-properties)
;(autoload 'use-package)
;(use-package "eglot")
;(package-activate 'eglot)
;(require 'eglot)
;(eglot-ensure)
;(find-file "vscode_ipc.sh")
;(package-install 'async-await)
;(add-to-list 'load-path ".")
;(print load-path)
;(require 'package)
;(require 'eglot)
;(load "eglot")
;(eglot-ensure)
;(sleep-for 20)
;(eglot-completion-at-point)
;(eglot t t t)
;(print (eglot--all-major-modes))
;(managed-major-mode project class contact &optional interactive)
;(setq project-root ".")
;(eglot "." t t t)
;(eglot t t)
;(eglot t t t t t)
;(eglot t t t)
;(add-hook 'sh-mode-hook 'eglot-ensure)
;(sh-mode)
;(sleep for a while...)
;(eglot-completion-at-point)
;(add-hook 'text-mode 'eglot-ensure)
;(add-hook 'sh-mode-hook 'eglot-ensure)
;(add-hook 'foo-mode-hook 'eglot-ensure)
;(print eglot-server-programs)
